title: Lono Collective
description: Cooperative Intelligence
url: "https://tektonics.github.io"
baseurl: "/lonocollective"

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
